apiVersion: v1
kind: Secret
metadata:
  name: go-srv-config
type: Opaque
data:
  mongodb.conn: {{ your_base64_encoded_secret }}
  rabbitmq.conn: YW1xcDovL2N2YnpybGZqOjFNNGdRR0hDX3NZMXFuSG01UERVcXhBazF2TWpMTURUQGFsYmF0cm9zcy5ybXEuY2xvdWRhbXFwLmNvbS9jdmJ6cmxmag==
